import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layouts/Header';
import { GlobalStyleContainer } from './GlobalStyle';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <GlobalStyleContainer>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </GlobalStyleContainer>
        </html>
    );
}
